### ISSUE TITLE
Error when resetting quota leaderboard automatically

### ISSUE THREAD

**Issue by ewang2002** [ewang2002/ToogaBooga#79]
```
C:\Users\user\desktop\projects\onerealm\out\utilities\TimeUtilities.js:140
            throw new Error("negative time");
                  ^

Error: negative time
    at Object.formatDuration (C:\Users\user\desktop\projects\onerealm\out\utilities\TimeUtilities.js:140:19)
    at Object.getQuotaLeaderboardEmbed (C:\Users\user\desktop\projects\onerealm\out\managers\QuotaManager.js:524:56)
    at Timeout.run [as _onTimeout] (C:\Users\ewang\user\projects\onerealm\out\managers\QuotaManager.js:647:45)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ewang2002** [comment]
This error should have been fixed
